hard_remove:
- c
- p
- q
- fecha
- i
- score
- fraude
- ymd
reject:
- ___random_con_2___
- ___random_cat_2___
- monto
- ___random_cat_1___
- day_of_week
- e
- vl_cat_last7d
- k
- hour_of_day
- j
- r
- period_of_day
- g
- ___random_con_1___
- h
- qty_cat_last7d
support:
- o
- f
- n
- a
- l
- m
- s
- br_qty_cat_last7d
- br_vl_cat_last7d
- d
- qty_fraud_cat_last7d
- b
- vl_fraud_cat_last7d
